import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";
import classes from "../styles/Home.module.css";

//https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl91lm1i926c601t2e4i91q6y/master

const graphCMS = new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl91lm1i926c601t2e4i91q6y/master"
);

const Query = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphCMS.request(Query);
  return {
    props: {
      posts: posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>GraphQl Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.mainContainer}>
        {posts.map((post) => (
          <BlogCard key={post.id} post={post} />
        ))}
      </main>
    </div>
  );
}
